#include "start_text\root.sqf"
#include "jip_teleport\root.sqf"
#include "marker_control\root.sqf"
#include "ao_limit\root.sqf"
#include "setup_timer\root.sqf"
#include "start_with_earplugs\root.sqf"
#include "start_on_safe\root.sqf"
#include "start_on_radio_channel\root.sqf"