////////////////////////////////////////////////////////
// GUI EDITOR OUTPUT START (by Sacher, v1.063, #Dyroxu)
////////////////////////////////////////////////////////
#define MEANCALCULATIONTIME 120
#define MEANAIMTIME 10
#define MEANSPOTTINGACCURACY 300
#define MEANPlOTTEDACCURACY 50
#define MAXSPOTTINGROUNDS 3
#define MEANFIRERATE 1
#define SPOTTINGROUNDSREQUIRED true
#define OBSACCURACY 100
#define OBSSPEED 30

#define MILSPERROUND  6400

#define VAR_SART_ARTINFIREMISSION "SARTisInAFiremission"
#define VAR_SART_ARTFIRERATE "SArtFireRate"
#define VAR_SART_ARTACCURACY "SArtAccuracy"
#define VAR_SART_ARTSPOTACCURACY "SArtSpottingAccuracy"
#define VAR_SART_ARTAIMSPEED "SArtAimSpeed"
#define VAR_SART_ARTCALCSPEED "SArtCalcSpeed"
#define VAR_SART_ARTCUSTOMNAME "SArtCustomName"
#define VAR_SART_ARTAMMO "SArtUnlimitedAmmo"
#define VAR_SART_ARTHASEH "SArtHasEventHandler"
#define VAR_SART_ARTFMTEXT "SArtyFiremissionText"
#define VAR_SART_ARTROUNDSFIRED "SArtFiremissionRoundsFired"
#define VAR_SART_FMHANDLE "SArtFiremissionHandle"
#define VAR_SART_CALLER "SArtCaller"
#define VAR_SART_IsAviable "SArtReady"


#define VAR_SART_OBSACCURACY "SObserverAccuracy"
#define VAR_SART_OBSSPEED "SObserverSpeed"

#define VAR_SART_OBSGUNS "SPlayerArtilleryGuns"
#define VAR_SART_PLAYERRECEIVEDGUNS "SPlayerReceived"
#define VAR_SART_PLAYERACEOPTIONS "SPlayerAceOptions"






#define ARTIWIDTHMAINSPACE  0.25
#define ARTIHEIGHTMAINSPACE  0.15
#define ARTILAYOUTHEIGHT   0.05
#define ARTILAYOUTHEIGHTSPACE   0.055
#define ARTIBORDERTHICKNESS   0.01
#define ARTILAYOUTWIDTH   0.15
#define ARTILAYOUTWIDTHSPACE   0.16

#define PFM_DIA_IDD_DISPLAY 765
#define PFM_DIA_IDC_GUNSELECT 29345
#define PFM_DIA_IDC_SHELLSELECT 29346
#define PFM_DIA_IDC_GRID 29347
#define PFM_DIA_IDC_DISPERSION 29348
#define PFM_DIA_IDC_BURSTNUMBER 29349
#define PFM_DIA_IDC_BURSTROUNDS 29350
#define PFM_DIA_IDC_BURSTDELAY 29351
#define PFM_DIA_IDC_SPOTTING 29352

#define LFM_DIA_IDD_DISPLAY 766
#define LFM_DIA_IDC_GUNSELECT 29353
#define LFM_DIA_IDC_SHELLSELECT 29354
#define LFM_DIA_IDC_STARTGRID 29355
#define LFM_DIA_IDC_ENDGRID 29356
#define LFM_DIA_IDC_BURSTNUMBER 29357
#define LFM_DIA_IDC_BURSTROUNDS 29358
#define LFM_DIA_IDC_BURSTDELAY 29359
#define LFM_DIA_IDC_SPOTTING 29360

#define BFM_DIA_IDD_DISPLAY 767
#define BFM_DIA_IDC_GUNSELECT 29361
#define BFM_DIA_IDC_SHELLSELECT 29362
#define BFM_DIA_IDC_STARTGRID 29363
#define BFM_DIA_IDC_ENDGRID 29364
#define BFM_DIA_IDC_BURSTNUMBER 29365
#define BFM_DIA_IDC_BURSTROUNDS 29366
#define BFM_DIA_IDC_BURSTDELAY  29367
#define BFM_DIA_IDC_SPOTTING  29368

#define DFM_DIA_IDD_DISPLAY 768
#define DFM_DIA_IDC_GUNSELECT 29369
#define DFM_DIA_IDC_SHELLSELECT 29370
#define DFM_DIA_IDC_GRID 29371
#define DFM_DIA_IDC_INNERRADIUS 29372
#define DFM_DIA_IDC_OUTERRADIUS 29373
#define DFM_DIA_IDC_BURSTNUMBER 29374
#define DFM_DIA_IDC_BURSTROUNDS 29375
#define DFM_DIA_IDC_BURSTDELAY  29376
#define DFM_DIA_IDC_SPOTTING  29377

#define MFM_DIA_IDD_DISPLAY 769
#define MFM_DIA_IDC_GUNSELECT 29378
#define MFM_DIA_IDC_SHELLSELECT 29379
#define MFM_DIA_IDC_NAME 29380
#define MFM_DIA_IDC_DISPERSION 29381
#define MFM_DIA_IDC_BURSTNUMBER 29383
#define MFM_DIA_IDC_BURSTROUNDS 29384
#define MFM_DIA_IDC_BURSTDELAY  29385
#define MFM_DIA_IDC_SPOTTING  29386

#define GSFM_DIA_IDD_DISPLAY 770
#define GSFM_DIA_IDC_GUNSELECT 29387
#define GSFM_DIA_IDC_SHELLSELECT 29388
#define GSFM_DIA_IDC_GRID 29389

#define PSFM_DIA_IDD_DISPLAY 771
#define PSFM_DIA_IDC_GUNSELECT 29390
#define PSFM_DIA_IDC_SHELLSELECT 29391
#define PSFM_DIA_IDC_GRID 29392
#define PSFM_DIA_IDC_MILS 29393
#define PSFM_DIA_IDC_DISTANCE 29394

#define POFM_DIA_IDD_DISPLAY 772
#define POFM_DIA_IDC_GUNSELECT 29395
#define POFM_DIA_IDC_SHELLSELECT 29396
#define POFM_DIA_IDC_GRID 29397
#define POFM_DIA_IDC_MILS 29398
#define POFM_DIA_IDC_DISTANCE 29399
#define POFM_DIA_IDC_DISPERSION 29400
#define POFM_DIA_IDC_BURSTNUMBER 29401
#define POFM_DIA_IDC_BURSTROUNDS 29402
#define POFM_DIA_IDC_BURSTDELAY 29403
#define POFM_DIA_IDC_SPOTTING 29405
